### PR TITLE
Migrate to N-API (fixes #6)

### LINKED ISSUE #6: Build fails with Node 12/Win
Hi,

thanks for making this project.

Unfortunately - I'm trying to rebuild the project for Node 12.7 build getting a lot of build errors (\*\*\* is used to replace actual paths below, please ignore)

System: Windows 10 1903 64-bit, Node 12.7.0, node-gyp 3.8.0, package: @ronomon/utimes@2.3.1

```
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  binding.cc
  win_delay_load_hook.cc
***\node_modules\@ronomon\utimes\binding.cc(151): error C2660: 'v8::Value::Uint32Value': function does not take 0 arguments [***\node_modules\@ronomon\utimes\build\binding.vcxproj]
  c:\users\***\.node-gyp\12.7.0\include\node\v8.h(2574): note: see declaration of 'v8::Value::Uint32Value' (compiling source file ..\binding.cc)
***\node_modules\@ronomon\utimes\binding.cc(151): error C2789: 'flags': an object of const-qualified type must be initialized [***\node_modules\@ronomon\utimes\build\binding.vcxproj]
  ***\node_modules\@ronomon\utimes\binding.cc(151): note: see declaration of 'flags'
***\node_modules\@ronomon\utimes\binding.cc(152): error C2660: 'v8::Value::IntegerValue': function does not take 0 arguments [***\node_modules\@ronomon\utimes\build\binding.vcxproj]
  c:\users\***\.node-gyp\12.7.0\include\node\v8.h(2572): note: see declaration of 'v8::Value::IntegerValue' (compiling source file ..\binding.cc)
***\node_modules\@ronomon\utimes\binding.cc(152): error C2789: 'btime': an object of const-qualified type must be initialized [***\node_modules\@ronomon\utimes\build\binding.vcxproj]
  ***\node_modules\@ronomon\utimes\binding.cc(152): note: see declaration of 'btime'
***\node_modules\@ronomon\utimes\binding.cc(153): error C2660: 'v8::Value::IntegerValue': function does not take 0 arguments [***\node_modules\@ronomon\utimes\build\binding.vcxproj]
  c:\users\***\.node-gyp\12.7.0\include\node\v8.h(2572): note: see declaration of 'v8::Value::IntegerValue' (compiling source file ..\binding.cc)
***\node_modules\@ronomon\utimes\binding.cc(153): error C2789: 'mtime': an object of const-qualified type must be initialized [***\node_modules\@ronomon\utimes\build\binding.vcxproj]
  ***\node_modules\@ronomon\utimes\binding.cc(153): note: see declaration of 'mtime'
***\node_modules\@ronomon\utimes\binding.cc(154): error C2660: 'v8::Value::IntegerValue': function does not take 0 arguments [***\node_modules\@ronomon\utimes\build\binding.vcxproj]
  c:\users\***\.node-gyp\12.7.0\include\node\v8.h(2572): note: see declaration of 'v8::Value::IntegerValue' (compiling source file ..\binding.cc)
***\node_modules\@ronomon\utimes\binding.cc(154): error C2789: 'atime': an object of const-qualified type must be initialized [***\node_modules\@ronomon\utimes\build\binding.vcxproj]
  ***\node_modules\@ronomon\utimes\binding.cc(154): note: see declaration of 'atime'
gyp ERR! build error
```

### PR DESCRIPTION
**Pull request by Jule-**
As mentioned it fixes #6, in other words it is working with Node V12.

### CODE REVIEW

**Comment by nikeee** [comment]
Is there anything that prevents this from merging?

**Comment by Jule-** [comment]
I don't know, no sign from @jorangreef since I have created it while I see that he continues telling people that he will do the N-API migration soon, likely by himself. I am disappointed, I tried to help...

**Comment by jorangreef** [comment]
Thanks @Jule- ! Sorry, somehow I missed this.

What I meant by moving to N-API, was moving to the pure C N-API, i.e. no more C++.

**Comment by Jule-** [comment]
@jorangreef no problem it happens. :wink: 

Why do you want to go for pure C N-API ? Is C++ [node-addon-api](https://github.com/nodejs/node-addon-api) not enough?

**Comment by jorangreef** [comment]
It's pure C :)

**Comment by edmundo096** [comment]
@jorangreef Do you think that we could use Jule-'s changes meanwhile the C version gets through?

I used Jule-'s commit (with `npm i https://github.com/Jule-/utimes.git#napi-migration`) and all went good enough, working correctly on node v12.3.1 on Win x64.

_Off-topic:_ I see @jorangreef  you have the `@ronomon/queue` as  a dependency. I think this is used only by the testing script, so it could be moved to be a devDependency (`npm i -D @ronomon/queue` should do the trick).  
This would make the package to have only 1 dependency, the `node-addon-api`.

_Off-topic 2:_ Like to your profile pic @Jule- !

Great compact utility library by the way

**Comment by jorangreef** [comment]
Thanks @edmundo096 , I don't want to push a new release unless it's N-API, and you should be able to cherry pick that PR if needed?

Thanks for the dev dependency tip. I will do that in the next N-API release. I hope to get to this soon!

**Comment by Jule-** [comment]
I do not understand why not releasing a intermediate version...

Whatever, it could be interesting to see the pure C improvement and which application could benefit of this C implementation performance upgrade if it really exists. I am not an expert on the subject but IMHO you will hit drives bottleneck way before the C++ overhead if you are trying to batch parallelized file changes. Just curious.

_Off-topic:_ Thanks @edmundo096! 😅

**Comment by jorangreef** [comment]
Thanks @Jule-,

It's not for performance. C is cleaner, especially using the N-API C library.

**Comment by Jule-** [comment]
Ok @jorangreef, looking forward to see your implementation! 🙂

Thanks again for this useful lib! 👍

**Comment by Offirmo** [comment]
Any news?

**Comment by jlindberg-oss** [comment]
Has anyone tried https://github.com/baileyherbert/utimes?  Looks like it's trying to be a fork of this lib to support modern node versions.

**Comment by Jule-** [comment]
@jlindberg-oss nope, didn't test it but it seems he has took my compatibility changes so it should be ok.

@baileyherbert thanks for doing it, I have been so close to do it... 😅 
And thanks for the credit! 😉

**Comment by Offirmo** [comment]
@jlindberg-oss I just tried https://github.com/baileyherbert/utimes and it works on latest macOs 👍
