### ISSUE TITLE
Not working on node v10.16.2

### ISSUE THREAD

**Issue by kamel3d** [ronomon/utimes#7]
electron/js2c/asar.js:155 Uncaught Error: The module '.../node_modules/@ronomon/utimes/binding.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 64. This version of Node.js requires
NODE_MODULE_VERSION 70. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).

**Comment by nikeee** [comment]
I also get some errors when compiling. I assume that is due to API changes in V8:
They ook like this:
```
../binding.cc:152:48: error: no matching function for call to ‘v8::Value::IntegerValue()’
  152 |   const uint64_t btime = info[2]->IntegerValue();
```
